version: '3.8'

services:
  config-server:
    image: mastermind007/job_portal-config-server:latest
    container_name: config-server
    ports:
      - "8888:8888"
    networks:
      - jobportal-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://config-server:8888/actuator/health"]
      interval: 10s
      retries: 5
      start_period: 20s  

  # User Service
  user-service:
    image: mastermind007/job_portal-user-service:latest
    container_name: user-service
    networks:
      - jobportal-network
    depends_on:
      config-server:
        condition: service_healthy
    environment:       
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
    ports:
      - "8100:8100"

networks:
  jobportal-network:
    external: true
