version: '3.8'

services:

# Naming Server Service (Eureka)
  naming-server:
    image: mastermind007/job_portal-naming-server:latest
    container_name: naming-server
    ports:
      - "8761:8761"
    networks:
      - jobportal-network

  # User Service
  user-service:
    image: mastermind007/job_portal-user-service:latest
    container_name: user-service
    networks:
      - jobportal-network
    depends_on:
      - naming-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka
    ports:
      - "8100:8100"


  # API Gateway Service
  api-gateway:
    image: mastermind007/job_portal-api-gateway:latest
    container_name: api-gateway
    networks:
      - jobportal-network
    depends_on:
      - naming-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka
    ports:
      - "8765:8765"

  # # Authentication Service
  authentication-service:
    image: mastermind007/job_portal-authentication-service:latest
    container_name: authentication-service
    networks:
      - jobportal-network
    depends_on:
      - naming-server  
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka
    ports:
      - "9100:9100"


networks:
  jobportal-network:
    external: true