spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - AuthenticationFilter

        - id: authentication-service
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path=/auth/**

      # globalcors:
      #   cors-configurations:
      #     "[/**]": # Apply to all routes
      #       allowedOriginPatterns:
      #         - "http://localhost:4200" # Replace with the frontend origin
      #       allowedMethods:
      #         - GET
      #         - POST
      #         - PUT
      #         - DELETE
      #       allowedHeaders: "*"
      #       allowCredentials: true

  application:
    name: api-gateway

server:
  port: 8765

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
