name: Build and Push Docker Image of naming server

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Build Naming Server
        run: |
          cd naming-server
          mvn clean package -DskipTests

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2


      - name: build docker image of config-server
        run: |
          cd config-server
          IMAGE_TAG=$(date +%Y%m%d)
          docker buildx build --platform linux/amd64,linux/arm64 -t mastermind007/job_portal-config-server:latest-${IMAGE_TAG} --push .

      - name: build docker image of naming-server
        run: |
          cd naming-server
          IMAGE_TAG=$(date +%Y%m%d)
          docker buildx build --platform linux/amd64,linux/arm64 -t mastermind007/job_portal-naming-server:latest-${IMAGE_TAG} --push .
          
          
      - name: build docker image of user-service
        run: |
          cd user-service
          IMAGE_TAG=$(date +%Y%m%d)
          docker buildx build --platform linux/amd64,linux/arm64 -t mastermind007/job_portal-user-service:latest-${IMAGE_TAG} --push .


      - name: build docker image of api-gateway
        run: |
          cd api-gateway
          IMAGE_TAG=$(date +%Y%m%d)
          docker buildx build --platform linux/amd64,linux/arm64 -t mastermind007/job_portal-api-gateway:latest-${IMAGE_TAG} --push .


      - name: build docker image of authentication-service
        run: |
          cd authentication-service
          IMAGE_TAG=$(date +%Y%m%d)
          docker buildx build --platform linux/amd64,linux/arm64 -t mastermind007/job_portal-authentication-service:latest-${IMAGE_TAG} --push .
